# Generated by Django 4.2.25 on 2025-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustbin',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dustbin',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
